//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeskShellEntities : DbContext
    {
        public DeskShellEntities()
            : base("name=DeskShellEntities")
        {
            
        }

        public DeskShellEntities(string connectionString) 
            : base(connectionString)
        {

        }
    
        public virtual DbSet<User> Users { get; set; }
    }
}
